[package]
name = "plastic-memories-font-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2"
image = "0.25.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
walkdir = "2"
